---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5ece7b6f18d252001249683d/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Site Configuration
  templates:
  - config
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*"
  exclude: "{inspirations/**/*, recipes/**/*, recipe/index.md, inspiration/index.md}"
  templates:
  - page
- type: document
  path: src/pages/recipe/index.md
  label: Recipe-page
- type: document
  path: src/pages/inspiration/index.md
  label: Inspiration-page
- type: directory
  path: src/pages/inspirations
  label: Inspirations
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/pages/recipes
  label: Recipes
  create: documents
  match: "**/*"
  templates:
  - project
upload_dir: ''
public_path: https://res.cloudinary.com/dnxlxtcb7/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_docker_image: node:10
  install_dependencies_command: npm install
  instant_preview_command: npm start
  mount_path: "/srv"
  working_dir: "/srv/src"
  preview_output_directory: "src/dist"
  preview_env:
  - ENV=staging
