---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5ece7b6f18d252001249683d/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Site Configuration
  templates:
  - config
- type: directory
  path: src/pages
  label: Page
  create: all
  match: "**/*"
  exclude: "{articles/**,recipes/**}"
  templates:
  - page
- type: directory
  path: src/pages/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/pages/recipes
  label: Recipes
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
