---
label: Project
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: The title of the project
    config:
      required: true
  - type: text
    name: subtitle
    label: Subtitle
    description: The text shown just below the project title.
  - type: text
    name: excerpt
    label: Excerpt
    description: The excerpt of the page displayed in meta data.
  - type: datetime
    name: date
    label: Date
    config:
      required: true
  - type: file
    name: thumb_image
    label: Featured Image
    description: The image shown in the project page.
  - type: file
    name: image
    label: Alternative Featured Image
    description: The image shown in the single project.
  - type: text
    name: template
    label: Template
    hidden: true
    default: project
    config:
      required: true
pages:
  - src/pages/articles/project-1.md
  - src/pages/articles/project-2.md
  - src/pages/articles/project-3.md
  - src/pages/articles/project-4.md
  - src/pages/articles/project-5.md
  - src/pages/articles/project-6.md
  - src/pages/articles/project-7.md
