---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
  description: The title of the project
  config:
    required: true
- name: subtitle
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Subtitle
- type: text
  name: excerpt
  label: Excerpt
  description: The excerpt of the page displayed in meta data.
- type: datetime
  name: date
  label: Date
  config:
    required: true
- name: cloudinary_url
  type: text
  config:
    required: false
  label: cloudinary_url
  default: https://res.cloudinary.com/dnxlxtcb7/image/upload
- type: file
  name: thumb_image
  label: Featured Image
  description: The image shown in the project page.
- type: file
  name: image
  label: Alternative Featured Image
  description: The image shown in the single project.
- type: text
  name: template
  label: Template
  hidden: false
  default: project
  config:
    required: true
pages:
- src/pages/recipes/001-turnip-gyoza.md
- src/pages/recipes/002-mushroom-steamed-dumpling.md
